name: TESTING NEW OUTPUTS - Rebuilder Test with Edge Globs

on: 
    workflow_dispatch:
    release:
        types: [created]
        
jobs:
    build:
        permissions:
          id-token: write # For signing
          contents: read # For repo checkout.
          actions: read # For getting workflow run info.
        uses: enteraga6/slsa-github-generator/.github/workflows/builder_bazel_slsa3.yml@feat-docker-input
        with:
            targets: "//src/..."
            docker-image: "docker.io/elzner2/test_image_bazel:v1.2"
            includes-java: true
            needs-runfiles: true
    download:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
            - id: download-att
              uses: actions/download-artifact@v3
              with:
                name: ${{ needs.build.outputs.attestations-download-name }}
            - id: download-bin 
              uses: actions/download-artifact@v3
              with:
                name: ${{ needs.build.outputs.binaries-download-name }}
            - name: Debug
              shell: bash
              run: |
                echo ${{ steps.download-att.outputs.download-path }}
                echo ${{ steps.download-bin.outputs.download-path }}
                echo ${{ needs.build.outputs.attestations-download-name }}
                echo ${{ needs.build.outputs.binaries-download-name }}
                echo ""
                ls -a
                
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    ${{ needs.build.outputs.attestations-download-name.name }}
                    ${{ needs.build.outputs.binaries-download-name.name }}
